In [2]:
#!/usr/bin/env python
import unitymouse.render as umr
import time
import numpy as np
from ibllib.atlas.regions import BrainRegions
from one.api import ONE
import ibllib.atlas as atlas

"""
Display all trajectories in one single brain volume
Author: Mayo, Gaelle, Dan
"""

import numpy as np

one = ONE()
ba = atlas.AllenAtlas(25)
traj_rep = one.alyx.rest('trajectories', 'list', provenance='Planned',
	x=-2243, y=-2000,  project='ibl_neuropixel_brainwide_01', use_cache=False)


In [3]:

umr.setup()

UnityMouse Renderer connected to server


In [24]:

entry_coords = ba.xyz2ccf(ins.entry)
tip_coords = ba.xyz2ccf(ins.tip)
print(entry_coords)
print(tip_coords)

[3150. 7200.  575.]
[4100.79763398 8072.11220698 4256.36698171]


In [25]:
dcoords = entry_coords-tip_coords

In [27]:
print(np.power(dcoords,2))

[  904016.14077578   760579.70156481 13552462.85403095]


In [28]:
np.sqrt(np.sum(np.power(entry_coords-tip_coords,2)))

3900.9048561034583

In [11]:
# TODO removing PID manually for sake of figure, but need to iron this out in Alyx
except_pid = ['8b735d77-b77b-4243-8821-37802bf402fe',
'94af9073-0914-4323-a90a-5eea1ef5f92c']

# temp_traj_rep = [traj_rep[0]]
count = 0

for traj in traj_rep:
    print('Trajectory: ' + traj['probe_insertion'])

    if traj['probe_insertion'] not in except_pid:
        temp_traj = one.alyx.rest('trajectories', 'list',
            provenance='Ephys aligned histology track',
            probe_insertion=traj['probe_insertion'], use_cache=False)
        if len(temp_traj) == 0:
            temp_traj = one.alyx.rest('trajectories', 'list', provenance='Histology track',
                probe_insertion=traj['probe_insertion'], use_cache=False)

            if len(temp_traj) == 0:
                continue

        if not temp_traj[0]['x']:
            continue

        ins = atlas.Insertion.from_dict(temp_traj[0])

        entry_coords = ba.xyz2ccf(ins.entry)
        tip_coords = ba.xyz2ccf(ins.tip)
        recording_size = np.sqrt(np.sum(np.power(entry_coords-tip_coords,2)))
        tip_angles = [ins.phi, ins.theta, ins.beta]

        probename = 'p'+str(count)
        count+=1
        umr.create_probes([probename])
        umr.set_probe_positions({probename:tip_coords.tolist()})
        umr.set_probe_angles({probename:tip_angles})
        umr.set_probe_size({probename:[0.07,recording_size,0.02]})


'''
Display structure meshes within the brain volume
You can download the mesh object for each brain structure here:
http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/annotation/ccf_2017/structure_meshes/
'''
br = BrainRegions()

data = {'VISa': True, 'CA1': True, 'DG': True, 'LP': True, 'PO': True}
umr.set_volume_visibility(data)
data = {'VISa': 'left', 'CA1': 'left', 'DG': 'left', 'LP': 'left', 'PO': 'left'}
umr.set_volume_style(data)

# data = {'root':True}
# umr.set_volume_visibility(data);



# target_area = ['VISa', 'CA1', 'DG', 'LP', 'PO']
# for target in target_area:
#     rindx_void = np.where(br.acronym == target)
#     idx = rindx_void[0][0]
#     mesh_id = br.id[idx]
#     # print(mesh_id) --> useful to download the specific mesh obj from the Allen website
#     color = br.rgb[idx, :]/255
#     path = f'/Users/gaelle/Desktop/Allenmesh/{mesh_id}.obj.txt'
#     rendering.add_mesh(fig, path, color, opacity=0.6)



Trajectory: 1e176f17-d00f-49bb-87ff-26d237b525f1
Trajectory: f936a701-5f8a-4aa1-b7a9-9f8b5b69bc7c
Trajectory: f86e9571-63ff-4116-9c40-aa44d57d2da9
Trajectory: 341ef9bb-25f9-4eeb-8f1d-bdd054b22ba8
Trajectory: 8d59da25-3a9c-44be-8b1a-e27cdd39ca34
Trajectory: 69f42a9c-095d-4a25-bca8-61a9869871d3
Trajectory: f2ee886d-5b9c-4d06-a9be-ee7ae8381114
Trajectory: 7f3dddf8-637f-47bb-a7b7-e303277b2107
Trajectory: b2746c16-7152-45a3-a7f0-477985638638
Trajectory: dc50c3de-5d84-4408-9725-22ae55b93522
Trajectory: b749446c-18e3-4987-820a-50649ab0f826
Trajectory: a3d13b05-bf4d-427a-a2d5-2fe050d603ec
Trajectory: 583ffb83-85df-4ac7-ae79-ddb7f751fb45
Trajectory: ca5764ea-a57e-49de-8156-84da18ad439f
Trajectory: febb430e-2d50-4f83-87a0-b5ffbb9a4943
Trajectory: c4f6665f-8be5-476b-a6e8-d81eeae9279d
Trajectory: 57656bee-e32e-4848-b924-0f6f18cfdfb1
Trajectory: dab512bd-a02d-4c1f-8dbc-9155a163efc0
Trajectory: eeb27b45-5b85-4e5c-b6ff-f639ca5687de
Trajectory: c17772a9-21b5-49df-ab31-3017addea12e
Trajectory: 7cbecb3f

In [13]:
umr.close()